from .HealthCheck import router as health
from .Root import router as root
from .StatusCheck import router as status
from .Webhook import router as webhook
from .MSGraphRouters.UserInvite import router as invite_user
from .MSGraphRouters.User import router as user
from .MSGraphRouters.Rule import router as rule
from .MSGraphRouters.Application import router as application
from .MSGraphRouters.File import router as file
from .MSGraphRouters.AircraftsAirlines import router as aircraftsairlines
from .MSGraphRouters.Claim import router as claim
from .Database import router as database
from .FlightRadar import router as flight_radar
